services:
  jsonpath:
    build:
      context: .  # 这是构建上下文，通常指向当前目录
      dockerfile: Dockerfile  # Dockerfile 的路径，可以省略（默认是 Dockerfile）
    image: jsonpath:10.2.0  # 构建的镜像标签
    container_name: jsonpath  # 容器名称
    platform: linux/amd64  # 指定平台架构为 amd64
    ports:
      - "3000:3000"  # 映射宿主机的 3000 端口到容器的 3000 端口
    restart: always  # 如果容器退出自动重启
