services:
  label-studio:
    image: heartexlabs/label-studio:1.15.0
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./data:/label-studio/data
    restart: unless-stopped
    stdin_open: true
    tty: true
